package model.entities;
// Generated 16.12.2017 13:25:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */

@Entity
@Table(name="user", catalog="db_users")
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String email;
     private String password;

    public User() {
    }

    public User(String username, String email, String password) {
       this.username = username;
       this.email = email;
       this.password = password;
    }
   
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", length=32)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "User{" + "id=" + id + ", username=" + username + ", "
                + "email=" + email + ", password=" + password + '}';
    }
    
    
}


